### ISSUE TITLE
Adonis/Addons/Drive cannot be extended, since their is no public interface to extend

### ISSUE THREAD

**Issue by medmans** [ahmadarif/adonis-drive-google#1]
Hello,

i'm receiving error after integrating the `'adonis-drive-google/providers/DriveProvider'` provider in the `app.js` file.

what type of reason can make this issue ?

**Comment by medmans** [comment]
i did `npm install @adonisjs/drive --save` and imported   `'@adonisjs/drive/providers/DriveProvider'` also to providers array ==> resolved !
Thanks

**Comment by ahmadarif** [comment]
Congratulations already successfully using this providers, btw sorry for late reply 🙏
